/* XPM */
static char * back_button_xpm[] = {
"nnnnnnnnnnnnnnnnnnnnnn;;         ;nnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnn;;            x t nnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnn;   ss               t ;nnnnnnnnnnnnnnnn",
"nnnnnnnnn;nnnn .t*  .  t   l*       tq*s ;nnnnnnnnnnnnn",
"nnnnnnnnnnnnn  sk    lllllllllllllt*   t  ;nnnnnnnnnnnn",
"nnnnnnnnnnn   *  tlllllllllllllllllll    t* nnnnnnnnnnn",
"nnnnnnnnnn tt  *lllllllllllllllllllllll *  txnnnnnnnnnn",
"nnnnnnnnn;tt  lllllllllllllllllllllllllll     ;nnnnnnnn",
"nnnnnnnn     lllllllllllllllllllllllllllll     .nnnnnnn",
"nnnnnnn;    llllllllllllllllllllllllllllllll*   nnnnnnn",
"nnnnn;    lllllllllllllllllllllllllllllllllll   ;;nnnnn",
"nnnnn;t*  llllllllllllllllllllllllllllllllllll  t;nnnnn",
"nnnn t   lllllllllllllllllllllllllllllllllllll  t ;nnnn",
"nnnn t  lllllllllllllllllllllllllllllllllllllll  t ;nnn",
"nnn; *slllllllllllllllllllllllllllllllllllllllll   ;nnn",
"nnn   *lllllllllllllllllllllslllllllllllllllllll    ;nn",
"nn q  lllllllllllllllllllll  llllllllllllllllllll    nn",
"n;s*  llllllllllllllllllll   lllllllllllllllllllllx* nn",
"n    llllllllllllllllllll    lllllllllllllllllllll   ;n",
"nt*  llllllllllllllllll      lllllllllllllllllllll    n",
"nt  llllllllllllllllll       llllllllllllllllllllll xt;",
";   lllllllllllllllll        llllllllllllllllllllll  * ",
"  * llllllllllllllll         llllllllllllllllllllll   t",
"t ttlllllllllllllll          llllllllllllllllllllll   t",
"    lllllllllllll                       llllllllllll   ",
"    llllllllllll        *               llllllllllll   ",
"   llllllllllll       x                 llllllllllll   ",
"   lllllllllll                          llllllllllll   ",
"   llllllllllll*              x         llllllllllll * ",
"   lllllllllllll                        llllllllllll   ",
"    lllllllllllll                       llllllllllll   ",
"    lllllllllllllll          llllllllllllllllllllll    ",
" t  llllllllllllllll         llllllllllllllllllllllt  t",
";   lllllllllllllllll        llllllllllllllllllllll x  ",
"n * llllllllllllllllll       llllllllllllllllllllll   ;",
"n t  llllllllllllllllll      lllllllllllllllllllll  t n",
"n;t  llllllllllllllllllll    lllllllllllllllllllll   ;n",
"n; t  llllllllllllllllllll   llllllllllllllllllllls  ;n",
"nn;* xlllllllllllllllllllll  llllllllllllllllllll * pnn",
"nnn    lllllllllllllllllllll lllllllllllllllllll  u nnn",
"nnn    lllllllllllllllllllllllllllllllllllllllll   ;nnn",
"nnn; t  lllllllllllllllllllllllllllllllllllllll  t ;nnn",
"nnnn;*   lllllllllllllllllllllllllllllllllllll    ;nnnn",
"nnnnn t   llllllllllllllllllllllllllllllllllll  u;nnnnn",
"nnnonn    llllllllllllllllllllllllllllllllllls  ;nnnnnn",
"nnnnnnn   **llllllllllllllllllllllllllllllllt*  nnnnnnn",
"nnnnnnnn   * lllllllllllllllllllllllllllll  * ;;nnnnnnn",
"nnnnnnnn.     lllllllllllllllllllllllllll     nnnnnnnnn",
"nnnnnnnnnn;tt*  lllllllllllllllllllllllt   u;nnnnnnnnnn",
"nnnnnnnnnn;; t    lllllllllllllllllll  * t ;nnnnnnnnnnn",
"nnnnnnnnnnnn;  u     lllllllllllll**      ;nnnnnnnnnnnn",
"nnnnnnnnnnnnn;; s      t   l     ttu  t ;;nnnnnnnnnnnnn",
"nnnnnnnnnnnnnnn;t utt           t    t nnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnn    t           ;nnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnn;         nnnnn;nnnnnnnnnnnnnnnn"};
